Fix import with -OO
When python is run with `-OO`, docstringings are removed and `__doc__` is set to
`None`. This makes `_format_docstring` fail with the following error:
```
>>> import threadpoolctl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 109, in <module>
    def threadpool_info():
  File "/home/peter/miniconda3/lib/python3.8/site-packages/threadpoolctl.py", line 101, in decorator
    o.__doc__ = o.__doc__.format(*args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'format'
```